# libraries
library(tidyverse)
library(lme4)
library(gt)
library(tidybayes)
library(RColorBrewer)
library(cowplot)
library(extrafont)
library(bayestestR)
library(data.table)
library(multcomp)
library(effects)
library(RSQLite)
library(standardize)
library(coefplot2)
library(arm)
library(sp)
library(mapview)
library(leaflet)
library(moveVis)
library(parallel)
library(doParallel)
library(aspace)
library(ggmap)
library(mgcv)
library(BaSTA)
library(kableExtra)
library(rptR)
library(patchwork)
library(ggpubr)
library(magick)
library(multipanelfigure)
library(grid)
library(broom.mixed)
library(partR2)
library(ggridges)
library(fGarch)
library(scales)
library(ggthemes)

# connect to CeutaCLOSED
CeutaCLOSED <- 
  dbConnect(SQLite(), 
            dbname = "/Users/Luke/Documents/Academic_Projects/Postdoc_Seewiesen/Ceuta_Open/Ceuta_CLOSED/data/Ceuta_CLOSED_version_releases/Ceuta_CLOSED_v2-0-0.sqlite")